"""
PROJECT EULER
Problem 2

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.

Author: Adam Beagle
"""

from Timer import Timer

################################################################################
def Prob2():
    fibs = [1, 1]
    ans = 0
    limit = 4000000

    while fibs[1] < limit:
        nxt = sum(fibs)
        fibs[0] = fibs[1]
        fibs[1] = nxt

        if fibs[1] % 2 == 0:
            ans += fibs[1]

    return ans

################################################################################
if __name__ == '__main__':
    try:
        with Timer() as timer:
            print 'Answer: ' + str(Prob2())
    finally:
        print 'Time: %.5fs' % timer.Interval
		
		

